"""Generate natives.h (ScriptHookV native wrappers) from alloc8or's natives.json.

Usage:
    python tools/gen_natives.py <natives.json> <out/natives.h>

The build runs this automatically; CMakeLists.txt pins the natives.json version from
https://github.com/alloc8or/gta5-nativedb-data
"""
import json
import pathlib
import sys

if len(sys.argv) != 3:
    sys.exit(__doc__)
SRC = pathlib.Path(sys.argv[1])
DST = pathlib.Path(sys.argv[2])

CPP_KEYWORDS = {
    "alignas", "alignof", "and", "asm", "auto", "bool", "break", "case", "catch", "char",
    "class", "const", "continue", "default", "delete", "do", "double", "else", "enum",
    "explicit", "export", "extern", "false", "float", "for", "friend", "goto", "if",
    "inline", "int", "long", "mutable", "namespace", "new", "not", "operator", "or",
    "private", "protected", "public", "register", "return", "short", "signed", "sizeof",
    "static", "struct", "switch", "template", "this", "throw", "true", "try", "typedef",
    "typeid", "typename", "union", "unsigned", "using", "virtual", "void", "volatile",
    "while", "xor", "near", "far", "min", "max",
}


def param_name(name: str, index: int) -> str:
    if not name:
        return f"p{index}"
    return name + "_" if name in CPP_KEYWORDS else name


def main() -> None:
    db = json.loads(SRC.read_text(encoding="utf-8"))
    out = [
        "// AUTO-GENERATED by tools/gen_natives.py from alloc8or/gta5-nativedb-data. Do not edit.",
        "#pragma once",
        "",
        '#include "nativeCaller.h"',
        "",
        "// Windows headers define macros that collide with some native names.",
        "#pragma push_macro(\"DELETE\")",
        "#undef DELETE",
        "",
    ]
    count = 0
    for ns, natives in db.items():
        out.append(f"namespace {ns}\n{{")
        for hash_, n in natives.items():
            ret = n["return_type"]
            params = [(p["type"], param_name(p["name"], i)) for i, p in enumerate(n["params"])]
            sig = ", ".join(f"{t} {nm}" for t, nm in params)
            args = "".join(f", {nm}" for _, nm in params)
            out.append(
                f"\tNATIVE_DECL {ret} {n['name']}({sig}) {{ return invoke<{ret}>({hash_}{args}); }}"
            )
            count += 1
        out.append("}\n")
    out.append("#pragma pop_macro(\"DELETE\")\n")
    DST.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {count} natives to {DST}")


if __name__ == "__main__":
    main()
